name: Deploy AWS

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/final-deploy.yml
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      cloud: aws
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
