name: Deploy Azure

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/final-deploy.yml
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      cloud: azure
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
