name: Deploy AWS

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
      ref:
        required: true
        type: string
      aws_region:         
        required: true
        type: string
      bucket_name:
        required: false
        type: string
      ami_id:
        required: false
        type: string
      instance_type:
        required: false
        type: string
      key_name:
        required: false
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/final-deploy.yml
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      cloud: aws
      aws_region: ${{ inputs.aws_region }}
      bucket_name: ${{ inputs.bucket_name }}
      ami_id: ${{ inputs.ami_id }}
      instance_type: ${{ inputs.instance_type }}
      key_name: ${{ inputs.key_name }}      
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
