name: Deploy GCP

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
      ref:
        required: true
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/final-deploy.yml
    with:
      repo: ${{ inputs.repo }}
      ref: ${{ inputs.ref }}
      cloud: gcp
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      GCP_WIP: ${{ secrets.GCP_WIP }}
      GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
